### ISSUE TITLE
Lower voltage PCF

### ISSUE THREAD

**Issue by exverse** [VoronDesign/Voron-Hardware#103]
I am wondering how to reduce voltage for PCF, i am running a 12v noctua fan.

**Comment by timmit99** [comment]
@exverse is this in genera? or relating to a specific device? a buck/boost converter on the + rail is the common way to reduce voltages for fans since the ground line is switched on the controller. instead of connecting the "+" leg of the fan to the control board, connect it to the output of a buck converter set to whatever voltage you want. The controller will switch the ground leg and the buck converter will drop the input (normally 24V) to the 12V needed for your fan to run properly.
